using CSharp_Query.Entity;

namespace CSharp_Query.DAO
{
    public class CountryDAO
    {
        public static List<Country> GetAllCountries() { 
            return new List<Country> {
                new Country("Afghanistan", "AF"),
                new Country("Albania", "AL"),
                new Country("Algeria", "DZ"),
                new Country("Andorra", "AD"),
                new Country("Angola", "AO"),
                new Country("Antigua and Barbuda", "AG"),
                new Country("Argentina", "AR"),
                new Country("Armenia", "AM"),
                new Country("Australia", "AU"),
                new Country("Austria", "AT"),
                new Country("Azerbaijan", "AZ"),
                new Country("Bahamas", "BS"),
                new Country("Bahrain", "BH"),
                new Country("Bangladesh", "BD"),
                new Country("Barbados", "BB"),
                new Country("Belarus", "BY"),
                new Country("Belgium", "BE"),
                new Country("Belize", "BZ"),
                new Country("Benin", "BJ"),
                new Country("Bhutan", "BT"),
                new Country("Bolivia", "BO"),
                new Country("Bosnia and Herzegovina", "BA"),
                new Country("Botswana", "BW"),
                new Country("Brazil", "BR"),
                new Country("Brunei", "BN"),
                new Country("Bulgaria", "BG"),
                new Country("Burkina Faso", "BF"),
                new Country("Burundi", "BI"),
                new Country("Cabo Verde", "CV"),
                new Country("Cambodia", "KH"),
                new Country("Cameroon", "CM"),
                new Country("Canada", "CA"),
                new Country("Central African Republic", "CF"),
                new Country("Chad", "TD"),
                new Country("Chile", "CL"),
                new Country("China", "CN"),
                new Country("Colombia", "CO"),
                new Country("Comoros", "KM"),
                new Country("Congo (Brazzaville)", "CG"),
                new Country("Congo (Kinshasa)", "CD"),
                new Country("Costa Rica", "CR"),
                new Country("Croatia", "HR"),
                new Country("Cuba", "CU"),
                new Country("Cyprus", "CY"),
                new Country("Czech Republic", "CZ"),
                new Country("Denmark", "DK"),
                new Country("Djibouti", "DJ"),
                new Country("Dominica", "DM"),
                new Country("Dominican Republic", "DO"),
                new Country("Ecuador", "EC"),
                new Country("Egypt", "EG"),
                new Country("El Salvador", "SV"),
                new Country("Equatorial Guinea", "GQ"),
                new Country("Eritrea", "ER"),
                new Country("Estonia", "EE"),
                new Country("Eswatini", "SZ"),
                new Country("Ethiopia", "ET"),
                new Country("Fiji", "FJ"),
                new Country("Finland", "FI"),
                new Country("France", "FR"),
                new Country("Gabon", "GA"),
                new Country("Gambia", "GM"),
                new Country("Georgia", "GE"),
                new Country("Germany", "DE"),
                new Country("Ghana", "GH"),
                new Country("Greece", "GR"),
                new Country("Grenada", "GD"),
                new Country("Guatemala", "GT"),
                new Country("Guinea", "GN"),
                new Country("Guinea-Bissau", "GW"),
                new Country("Guyana", "GY"),
                new Country("Haiti", "HT"),
                new Country("Honduras", "HN"),
                new Country("Hungary", "HU"),
                new Country("Iceland", "IS"),
                new Country("India", "IN"),
                new Country("Indonesia", "ID"),
                new Country("Iran", "IR"),
                new Country("Iraq", "IQ"),
                new Country("Ireland", "IE"),
                new Country("Israel", "IL"),
                new Country("Italy", "IT"),
                new Country("Jamaica", "JM"),
                new Country("Japan", "JP"),
                new Country("Jordan", "JO"),
                new Country("Kazakhstan", "KZ"),
                new Country("Kenya", "KE"),
                new Country("Kiribati", "KI"),
                new Country("Kuwait", "KW"),
                new Country("Kyrgyzstan", "KG"),
                new Country("Laos", "LA"),
                new Country("Latvia", "LV"),
                new Country("Lebanon", "LB"),
                new Country("Lesotho", "LS"),
                new Country("Liberia", "LR"),
                new Country("Libya", "LY"),
                new Country("Liechtenstein", "LI"),
                new Country("Lithuania", "LT"),
                new Country("Luxembourg", "LU"),
                new Country("Madagascar", "MG"),
                new Country("Malawi", "MW"),
                new Country("Malaysia", "MY"),
                new Country("Maldives", "MV"),
                new Country("Mali", "ML"),
                new Country("Malta", "MT"),
                new Country("Marshall Islands", "MH"),
                new Country("Mauritania", "MR"),
                new Country("Mauritius", "MU"),
                new Country("Mexico", "MX"),
                new Country("Micronesia", "FM"),
                new Country("Moldova", "MD"),
                new Country("Monaco", "MC"),
                new Country("Mongolia", "MN"),
                new Country("Montenegro", "ME"),
                new Country("Morocco", "MA"),
                new Country("Mozambique", "MZ"),
                new Country("Myanmar", "MM"),
                new Country("Namibia", "NA"),
                new Country("Nauru", "NR"),
                new Country("Nepal", "NP"),
                new Country("Netherlands", "NL"),
                new Country("New Zealand", "NZ"),
                new Country("Nicaragua", "NI"),
                new Country("Niger", "NE"),
                new Country("Nigeria", "NG"),
                new Country("North Korea", "KP"),
                new Country("North Macedonia", "MK"),
                new Country("Norway", "NO"),
                new Country("Oman", "OM"),
                new Country("Pakistan", "PK"),
                new Country("Palau", "PW"),
                new Country("Panama", "PA"),
                new Country("Papua New Guinea", "PG"),
                new Country("Paraguay", "PY"),
                new Country("Peru", "PE"),
                new Country("Philippines", "PH"),
                new Country("Poland", "PL"),
                new Country("Portugal", "PT"),
                new Country("Qatar", "QA"),
                new Country("Romania", "RO"),
                new Country("Russia", "RU"),
                new Country("Rwanda", "RW"),
                new Country("Saint Kitts and Nevis", "KN"),
                new Country("Saint Lucia", "LC"),
                new Country("Saint Vincent and the Grenadines", "VC"),
                new Country("Samoa", "WS"),
                new Country("San Marino", "SM"),
                new Country("Sao Tome and Principe", "ST"),
                new Country("Saudi Arabia", "SA"),
                new Country("Senegal", "SN"),
                new Country("Serbia", "RS"),
                new Country("Seychelles", "SC"),
                new Country("Sierra Leone", "SL"),
                new Country("Singapore", "SG"),
                new Country("Slovakia", "SK"),
                new Country("Slovenia", "SI"),
                new Country("Solomon Islands", "SB"),
                new Country("Somalia", "SO"),
                new Country("South Africa", "ZA"),
                new Country("South Korea", "KR"),
                new Country("South Sudan", "SS"),
                new Country("Spain", "ES"),
                new Country("Sri Lanka", "LK"),
                new Country("Sudan", "SD"),
                new Country("Suriname", "SR"),
                new Country("Sweden", "SE"),
                new Country("Switzerland", "CH"),
                new Country("Syria", "SY"),
                new Country("Taiwan", "TW"),
                new Country("Tajikistan", "TJ"),
                new Country("Tanzania", "TZ"),
                new Country("Thailand", "TH"),
                new Country("Timor-Leste", "TL"),
                new Country("Togo", "TG"),
                new Country("Tonga", "TO"),
                new Country("Trinidad and Tobago", "TT"),
                new Country("Tunisia", "TN"),
                new Country("Turkey", "TR"),
                new Country("Turkmenistan", "TM"),
                new Country("Tuvalu", "TV"),
                new Country("Uganda", "UG"),
                new Country("Ukraine", "UA"),
                new Country("United Arab Emirates", "AE"),
                new Country("United Kingdom", "GB"),
                new Country("United States", "US"),
                new Country("Uruguay", "UY"),
                new Country("Uzbekistan", "UZ"),
                new Country("Vanuatu", "VU"),
                new Country("Vatican City", "VA"),
                new Country("Venezuela", "VE"),
                new Country("Vietnam", "VN"),
                new Country("Yemen", "YE"),
                new Country("Zambia", "ZM"),
                new Country("Zimbabwe", "ZW")
            };
        }

        public static List<String> MockDataAllCountry() {
            return new List<String>
            {
                "AF", "AL", "DZ", "AD", "AO", "AG", "AR", "AM", "AU", "AT",
                "AZ", "BS", "BH", "BD", "BB", "BY", "BE", "BZ", "BJ", "BT",
                "BO", "BA", "BW", "BR", "BN", "BG", "BF", "BI", "CV", "KH",
                "CM", "CA", "CF", "TD", "CL", "CN", "CO", "KM", "CG", "CD",
                "CR", "HR", "CU", "CY", "CZ", "DK", "DJ", "DM", "DO", "EC",
                "EG", "SV", "GQ", "ER", "EE", "SZ", "ET", "FJ", "FI", "FR",
                "GA", "GM", "GE", "DE", "GH", "GR", "GD", "GT", "GN", "GW",
                "GY", "HT", "HN", "HU", "IS", "IN", "ID", "IR", "IQ", "IE",
                "IL", "IT", "JM", "JP", "JO", "KZ", "KE", "KI", "KW", "KG",
                "LA", "LV", "LB", "LS", "LR", "LY", "LI", "LT", "LU", "MG",
                "MW", "MY", "MV", "ML", "MT", "MH", "MR", "MU", "MX", "FM",
                "MD", "MC", "MN", "ME", "MA", "MZ", "MM", "NA", "NR", "NP",
                "NL", "NZ", "NI", "NE", "NG", "KP", "MK", "NO", "OM", "PK",
                "PW", "PA", "PG", "PY", "PE", "PH", "PL", "PT", "QA", "RO",
                "RU", "RW", "KN", "LC", "VC", "WS", "SM", "ST", "SA", "SN",
                "RS", "SC", "SL", "SG", "SK", "SI", "SB", "SO", "ZA", "KR",
                "SS", "ES", "LK", "SD", "SR", "SE", "CH", "SY", "TW", "TJ",
                "TZ", "TH", "TL", "TG", "TO", "TT", "TN", "TR", "TM", "TV",
                "UG", "UA", "AE", "GB", "US", "UY", "UZ", "VU", "VA", "VE",
                "VN", "YE", "ZM", "ZW", "XX"
            };
        }

        public static List<String> MockDataCountry()
        {
            return new List<String>
            {
                "PH", "PL", "PT", "QA", "RO",
                "RU", "RW", "KN", "LC", "VC", 
            }; 
        }

    }
}
